### ISSUE TITLE
canny method fails

### ISSUE THREAD

**Issue by sciunto** [sciunto-org/pendantdrop#18]
Code to reproduce

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os.path
import numpy as np
import matplotlib.pyplot as plt

from scipy.optimize import minimize


from drop.io import load_image
from drop.improcessing import fit_circle_tip, detect_edges, guess_angle
from drop.optimize import (young_laplace,
                               deviation_edge_model_simple,
                               deviation_edge_model_full)


from drop.optimize.deviation import orthogonal_RMS, radial_RMS


def main():
    # image_path = os.path.join('data', 'uEye_Image_002767.png')
    # zoom = ((714, 1920), (920, 1830))
    image_path = os.path.join('data', 'uEye_Image_000827.png')
    zoom = ([100, 1312], [400, 1900])
    calib = 0.00124 / 400  # mm / px
    # Arbitrary first guess for gamma
    initial_surface_tension = 0.04  # N/m
    surface_tension_range = (0.02, 0.1)

    image1 = load_image(image_path, region=zoom)

    edges, RZ_edges = detect_edges(image1, method='canny')

    # Guess parameters
    center_Z, center_R, radius = fit_circle_tip(edges.shape,
                                                RZ_edges,
                                                method='ransac',
                                                debug=False)
    theta = guess_angle(edges, center_Z, center_R)

    # Note that below the method method='SLSQP' can be used also.

    # Step 1: consider only the surface tension
    # as it is not guessed so far
    ini_variables = np.array((initial_surface_tension))
    res = minimize(deviation_edge_model_simple,
                   ini_variables,
                   args=(theta, center_R, center_Z,
                         radius, RZ_edges, calib),
                   method='L-BFGS-B',
                   bounds=(surface_tension_range,),
                   options={'maxiter': 10,
                            'ftol': 1e-2,
                            'disp': True})
    guessed_surface_tension = res.x[0]
    print(f'Step 1-RMS: {res.fun}')

    # Step 2: consider all the parameters
    ini_variables2 = np.array((guessed_surface_tension,
                               theta, center_R, center_Z, radius,))
    param_bounds = ((guessed_surface_tension-2e-3, guessed_surface_tension+2e-3),
                    (theta*0.7, theta*1.3),
                    (center_R-5, center_R+5),
                    (center_Z-5, center_Z+5),
                    (radius-10, radius+10),
                    )

    res = minimize(deviation_edge_model_full,
                   ini_variables2,
                   args=(RZ_edges, calib),
                   method='L-BFGS-B',
                   bounds=param_bounds,
                   options={'maxiter': 100,
                            'ftol': 1e-6,
                            'disp': True})
    optimal_variables = res.x
    print(f'Step 2-ini params BFGS: {ini_variables2}')
    print(f'Step 2-opt params BFGS: {optimal_variables}')
    print(f'Step 2-RMS: {res.fun}')

    # Plot
    RZ_model = young_laplace(*optimal_variables,
                             RZ_edges, calib, num_points=1e4)

    oRMS = orthogonal_RMS(RZ_model, RZ_edges)
    rRMS = radial_RMS(RZ_model, RZ_edges)
    print(f'OrthoRMS: {oRMS}, RadialRMS {rRMS}')

    plt.figure()
    ax = plt.axes()
    plt.imshow(image1, cmap='gray')
    circle = plt.Circle((center_R, center_Z), radius=radius,
                        color='c', fill=False)
    ax.add_patch(circle)
    plt.plot(*RZ_edges, '*g', markersize=1)
    plt.plot(*RZ_model, 'r-', markersize=2)
    plt.plot(center_R, center_Z, 'bo')
    plt.title(f'Gamma = {optimal_variables[0]:.4} N/m')
    plt.show()


if __name__ == '__main__':
    main()
```

Output
```
/home/fr/github/pendantdrop/drop/optimize/optimization.py:16: RuntimeWarning: invalid value encountered in greater
  aa = np.where(Z > np.max(Z_edges))
/home/fr/github/pendantdrop/drop/utils.py:44: RuntimeWarning: invalid value encountered in less
  mask_left = R < R[Z.argmin()]
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    main()
  File "main.py", line 47, in main
    res = minimize(deviation_edge_model_simple,
  File "/home/fr/.local/share/virtualenvs/science/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 609, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/fr/.local/share/virtualenvs/science/lib/python3.8/site-packages/scipy/optimize/lbfgsb.py", line 345, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/fr/.local/share/virtualenvs/science/lib/python3.8/site-packages/scipy/optimize/lbfgsb.py", line 290, in func_and_grad
    f = fun(x, *args)
  File "/home/fr/.local/share/virtualenvs/science/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 327, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/fr/github/pendantdrop/drop/optimize/optimization.py", line 125, in deviation_edge_model_simple
    return RMS(RZ, RZ_edges)
  File "/home/fr/github/pendantdrop/drop/optimize/deviation.py", line 62, in radial_RMS
    e_left = _radial_squared_distance(R_left, Z_left, R_edges_left, Z_edges_left)
  File "/home/fr/github/pendantdrop/drop/optimize/deviation.py", line 31, in _radial_squared_distance
    R_theo_interpolator = interp1d(Z, R, kind='linear',
  File "/home/fr/.local/share/virtualenvs/science/lib/python3.8/site-packages/scipy/interpolate/interpolate.py", line 468, in __init__
    self._y = self._reshape_yi(self.y)
  File "/home/fr/.local/share/virtualenvs/science/lib/python3.8/site-packages/scipy/interpolate/polyint.py", line 111, in _reshape_yi
    return yi.reshape((yi.shape[0], -1))
ValueError: cannot reshape array of size 0 into shape (0,newaxis)
```

**Comment by sciunto** [comment]
The issue is in guess_angle that returns a nan.
